# Generated by Django 3.0.6 on 2020-06-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Employeur'},
        ),
    ]
