# Generated by Django 3.0.6 on 2020-06-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200606_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Administrateur'},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate'},
        ),
        migrations.RemoveField(
            model_name='admin',
            name='super',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
