# Generated by Django 2.2.6 on 2020-08-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='candidates/cvs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%M/%D/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('company_type', models.CharField(blank=True, max_length=128, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='EvaluationForOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('level', models.CharField(blank=True, max_length=128, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=128, null=True)),
                ('salary', models.CharField(blank=True, max_length=128, null=True)),
                ('post', models.CharField(blank=True, max_length=128)),
                ('offer_type', models.CharField(blank=True, choices=[('emploi', 'Emploi'), ('stage', 'stage')], max_length=32, null=True)),
                ('offer_category', models.CharField(blank=True, choices=[('it', 'IT'), ('aucune', 'Aucune'), ('hotelerie', 'Hotelerie'), ('enseignement', 'Enseignement'), ('immobilier', 'Immobilier'), ('finance', 'Finance'), ('medicale', 'Medicale'), ('ingenieurie', 'Ingenieurie')], max_length=32, null=True)),
                ('competence', models.CharField(max_length=128, null=True)),
                ('experience', models.CharField(max_length=32, null=True)),
                ('begins', models.DateField(blank=True, null=True)),
                ('ends', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestForOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joboffer.Offer')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.Test')),
            ],
        ),
    ]
