# Generated by Django 3.0.6 on 2020-06-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joboffer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0001_initial'),
        ('evaluation', '0002_auto_20200617_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='applicants',
            field=models.ManyToManyField(related_name='candidates_applying_for_offer', through='joboffer.Apply', to='registration.Candidate'),
        ),
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joboffer.Company'),
        ),
        migrations.AddField(
            model_name='offer',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_created_offer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='tests',
            field=models.ManyToManyField(blank=True, through='joboffer.TestForOffer', to='evaluation.Test'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_who_created_the_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='offer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='joboffer.Offer'),
        ),
        migrations.AddField(
            model_name='apply',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.Candidate'),
        ),
        migrations.AddField(
            model_name='apply',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joboffer.Offer'),
        ),
    ]
