# Generated by Django 3.0.6 on 2020-06-11 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0002_auto_20200605_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('company_type', models.CharField(blank=True, max_length=128, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='competence',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='experience',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='level',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='post',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='offer',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%M/%D/')),
                ('offer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='joboffer.Offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joboffer.Company'),
        ),
    ]
