# Generated by Django 3.0.6 on 2020-06-11 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200609_0716'),
        ('joboffer', '0003_auto_20200611_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_who_created_the_company', to='registration.Employer'),
        ),
        migrations.AddField(
            model_name='company',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
