# Generated by Django 2.2.6 on 2020-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0004_offer_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_category',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('aucune', 'Aucune'), ('hotelerie', 'Hotelerie'), ('enseignement', 'Enseignement'), ('immobilier', 'Immobilier'), ('finance', 'Finance'), ('medicale', 'Medicale'), ('ingenieurie', 'Ingenieurie')], max_length=32, null=True),
        ),
    ]
