# Generated by Django 2.2.6 on 2020-08-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0004_remove_evaluation_test'),
        ('joboffer', '0005_auto_20200809_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='evaluations',
            field=models.ManyToManyField(blank=True, to='evaluation.Evaluation'),
        ),
    ]
