# Generated by Django 3.0.6 on 2020-06-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0006_auto_20200611_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
