# Generated by Django 2.2.6 on 2020-08-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0006_offer_evaluations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='evaluations',
        ),
    ]
