# Generated by Django 3.0.6 on 2020-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0007_apply_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
