# Generated by Django 2.2.6 on 2020-08-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluation', '0004_remove_evaluation_test'),
        ('joboffer', '0007_remove_offer_evaluations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationForOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluation.Evaluation')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='joboffer.Offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='evaluations',
            field=models.ManyToManyField(blank=True, through='joboffer.EvaluationForOffer', to='evaluation.Evaluation'),
        ),
    ]
